/* Automatically generated by './build/bin/build-ts.js' */
import { Button } from './button';
import { ButtonGroup } from './button-group';
import { Icon } from './icon';
import { Confirm as ZZConfirm } from './confirm';
import {
  Message as ZZMessage,
  MessageOptions
} from './message';
import {
  Notification as ZZNotification,
  NotificationOptions
} from './notification';
import { FormRule, FormRules } from './form';

export const Message: ZZMessage;
export const Notification: ZZNotification;
export const Confirm: ZZConfirm;

export {
  Button,
  ButtonGroup,
  Icon,
  FormRule,
  FormRules,
  NotificationOptions,
  MessageOptions,
};

export declare function install(vue: any): void;

declare module 'vue/types/vue' {
  interface Vue {
    $zz: {
      confirm: ZZConfirm
      message: ZZMessage
      notify: ZZNotification
    }
  }
}
