/* Automatically generated by './build/bin/build-entry.js' */
import Button from 'components/button'
import ButtonGroup from 'components/button-group'
import Icon from 'components/icon'
import CollapseTransition from './transitions/collapse-transition'

const components = [Button, ButtonGroup, Icon, CollapseTransition]

export function install(Vue: any) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
  // const $zz = {
  //   confirm: Confirm,
  //   notify: Notification,
  //   message: Message,
  // };

  // Vue.prototype.$zz = $zz;
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export { Button, ButtonGroup, Icon, CollapseTransition }

export default {
  version: '1.0.0',
  install,
}
