name: Gh Pages Deploy #action名称
on:
  push:
    braches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #运行环境
    name: build
    steps:
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v2 #这里使用了github官方提供的action,checkout项目到虚拟机上
        with:
          persist-credentials: false
      - name: Install Dependencies
        run: npm run bootstrap
      - name: Build And Deploy
        run: npm run deploy
